(function () {
"use strict";
var SUPABASE_URL="https://jjfxjfkomcjgmhjzhwmc.supabase.co";
var SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqZnhqZmtvbWNqZ21oanpod21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1NDI4MzYsImV4cCI6MjA5OTExODgzNn0.IDw7xJrgxvvi1_u-hI8lybsw5sMNSQN1lNUreCLUvb0";
var PRODUCTS=[["bandera", "La Bandera Dominicana"], ["moro-guandules-bandera", "Moro de Guandules (Bandera)"], ["moro-habichuelas-bandera", "Moro de Habichuelas (Bandera)"], ["mofongo", "Mofongo"], ["pescado-frito-entero", "Pescado Frito Entero"], ["chuleta-plancha", "Chuleta a la Plancha"], ["pica-pollo", "Pica Pollo"], ["alitas", "Alitas"], ["yaroa", "Yaroa"], ["fritura-combinada", "Fritura Combinada"], ["sancocho", "Sancocho"], ["tres-golpes", "Tres Golpes"], ["sandwich-tres-golpes", "Sandwis de 3 Golpes"], ["chimi", "Chimi"], ["tostada-dominicana", "Tostada Dominicana"], ["burritos", "Burritos"], ["quesadilla", "Quesadilla"], ["mini-bandera-kids", "Mini Bandera"], ["pica-pollo-kid", "Pica Pollo de Niño"], ["quesadilla-kids", "Quesadilla de Niño"], ["tostones-salami-kids", "Tostones con Salami"], ["chulitos-de-yuca", "Chulitos de Yuca"], ["quipes", "Quipes"], ["pastel-en-hoja", "Pastel en Hoja"], ["empanada-dominicana", "Empanada Dominicana"], ["jugo-guanabana", "Jugo Natural de Guanábana"], ["jugo-chinola", "Jugo Natural de Chinola"], ["jugo-tamarindo", "Jugo Natural de Tamarindo"], ["batida-zapote", "Batida de Zapote"], ["batida-de-lechosa", "Batida de Lechosa"]];
var PIN="5425";
var orders=[];
var hiddenKitchen={};
function byId(id){return document.getElementById(id);}
function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function money(v){var n=Number(v||0);return "$"+n.toFixed(2);}
function request(method,path,body,done){var xhr=new XMLHttpRequest();xhr.open(method,SUPABASE_URL+"/rest/v1/"+path,true);xhr.setRequestHeader("apikey",SUPABASE_KEY);xhr.setRequestHeader("Authorization","Bearer "+SUPABASE_KEY);xhr.setRequestHeader("Content-Type","application/json");xhr.setRequestHeader("Prefer","return=representation,resolution=merge-duplicates");xhr.onreadystatechange=function(){if(xhr.readyState!==4)return;if(xhr.status>=200&&xhr.status<300){var data=null;try{data=xhr.responseText?JSON.parse(xhr.responseText):null;}catch(e){}done(null,data);}else{done(new Error("Error "+xhr.status+": "+xhr.responseText));}};xhr.send(body?JSON.stringify(body):null);}
function orderType(o){var t=o.order_type||"";if(!t&&o.items&&o.items[0])t=o.items[0].orderType||"";return t==="dine-in"?"Para aquí":t==="takeout"?"Para llevar":"No indicado";}
function payment(o){return o.payment_method==="cash"?"Efectivo":o.payment_method==="card"?"Tarjeta":"No indicado";}
function status(o){return o.status==="ready"?"Listo":o.status==="accepted"?"Aceptado":"Nuevo";}
function normalize(row){return {id:String(row.public_id==null?row.id:row.public_id),databaseId:row.id,createdAt:row.created_at,customer:{name:row.customer_name||"",phone:row.customer_phone||""},items:row.items||[],totals:{total:row.total||0},paymentMethod:row.payment_method||"",orderType:row.order_type||"",status:row.status||"new"};}
function itemHtml(item){var h='<div class="item"><strong>'+esc(item.quantity||1)+'x '+esc(item.name||"")+'</strong>';var a=item.selections||[],i;for(i=0;i<a.length;i++)h+='<p>'+esc(a[i].group)+': '+esc(a[i].name)+'</p>';a=item.extras||[];for(i=0;i<a.length;i++)h+='<p>Extra: '+esc(a[i].name)+'</p>';if(item.notes)h+='<p><strong>Nota:</strong> '+esc(item.notes)+'</p>';return h+'</div>';}
function render(){var h='',k='',i,j,o,cls;for(i=0;i<orders.length;i++){o=orders[i];cls=o.status==="ready"?" ready":o.status==="accepted"?" accepted":"";h+='<div class="order'+cls+'"><div class="row"><div class="left"><strong>Pedido '+esc(o.id)+'</strong><p>'+esc(new Date(o.createdAt).toLocaleString())+'</p></div><div class="right status">'+status(o)+'</div><div class="clear"></div></div><p><strong>'+esc(o.customer.name||"Sin nombre")+'</strong> · '+esc(o.customer.phone||"Sin teléfono")+'</p><p><strong>Tipo:</strong> '+orderType(o)+' · <strong>Pago:</strong> '+payment(o)+'</p>';for(j=0;j<o.items.length;j++)h+=itemHtml(o.items[j]);h+='<h2>Total '+money(o.totals.total)+'</h2>';if(o.status==="new")h+='<button data-action="accept" data-id="'+esc(o.id)+'">Aceptar</button>';if(o.status!=="ready")h+='<button class="secondary" data-action="ready" data-id="'+esc(o.id)+'">Marcar listo</button>';h+='<button class="danger" data-action="delete" data-id="'+esc(o.id)+'">Entregado / quitar</button></div>';if(!hiddenKitchen[o.id]){k+='<div class="order"><strong>Pedido '+esc(o.id)+'</strong>';for(j=0;j<o.items.length;j++)k+=itemHtml(o.items[j]);k+='<button class="secondary" data-action="hide" data-id="'+esc(o.id)+'">Terminado en cocina</button></div>';}}byId("ordersList").innerHTML=h||'<div class="card">No hay pedidos.</div>';byId("kitchenList").innerHTML=k||'<div class="card">No hay comandas.</div>';}
function loadOrders(){byId("connectionMessage").innerHTML="Actualizando…";request("GET","orders?select=*&order=created_at.desc",null,function(err,data){if(err){byId("connectionMessage").className="error";byId("connectionMessage").innerHTML=esc(err.message);return;}orders=[];var i;for(i=0;i<(data||[]).length;i++)orders.push(normalize(data[i]));byId("connectionMessage").className="ok";byId("connectionMessage").innerHTML="Conectado. Última actualización: "+new Date().toLocaleTimeString();render();});}
function findOrder(id){var i;for(i=0;i<orders.length;i++)if(String(orders[i].id)===String(id))return orders[i];return null;}
function changeStatus(id,next){var o=findOrder(id);if(!o)return;request("PATCH","orders?id=eq."+encodeURIComponent(o.databaseId),{status:next,updated_at:new Date().toISOString()},function(err){if(err)alert(err.message);loadOrders();});}
function removeOrder(id){var o=findOrder(id);if(!o||!confirm("¿Quitar este pedido para todos?"))return;request("DELETE","orders?id=eq."+encodeURIComponent(o.databaseId),null,function(err){if(err)alert(err.message);loadOrders();});}
function renderAvailability(map){var h='',i,p,checked;for(i=0;i<PRODUCTS.length;i++){p=PRODUCTS[i];checked=map[p[0]]!==false;h+='<label class="availability"><input type="checkbox" data-product="'+esc(p[0])+'" '+(checked?'checked="checked"':'')+'> '+esc(p[1])+'</label>';}byId("availabilityList").innerHTML=h;}
function loadAvailability(){request("GET","product_availability?select=product_id,available",null,function(err,data){var map={},i;if(err){byId("availabilityList").innerHTML='<p class="error">'+esc(err.message)+'</p>';return;}for(i=0;i<(data||[]).length;i++)map[data[i].product_id]=data[i].available!==false;renderAvailability(map);});}
function setAvailability(id,available){request("POST","product_availability?on_conflict=product_id",{product_id:id,available:available,updated_at:new Date().toISOString()},function(err){if(err)alert(err.message);});}
function switchTab(name){var buttons=document.querySelectorAll('[data-tab]'),panels=document.querySelectorAll('.panel'),i;for(i=0;i<buttons.length;i++)buttons[i].className=buttons[i].getAttribute('data-tab')===name?'active':'';for(i=0;i<panels.length;i++)panels[i].className='panel'+(panels[i].id===name+'Panel'?' active':'');if(name==='availability')loadAvailability();}
byId("pinForm").onsubmit=function(e){if(e)e.preventDefault();if(byId("pinInput").value!==PIN){byId("pinError").style.display="block";return false;}byId("login").style.display="none";byId("admin").style.display="block";loadOrders();setInterval(loadOrders,5000);return false;};
byId("refreshBtn").onclick=loadOrders;
document.onclick=function(e){e=e||window.event;var t=e.target||e.srcElement,action,id,tab;while(t&&t!==document){action=t.getAttribute&&t.getAttribute("data-action");tab=t.getAttribute&&t.getAttribute("data-tab");if(action||tab)break;t=t.parentNode;}if(tab){switchTab(tab);return;}if(!action)return;id=t.getAttribute("data-id");if(action==="accept")changeStatus(id,"accepted");else if(action==="ready")changeStatus(id,"ready");else if(action==="delete")removeOrder(id);else if(action==="hide"){hiddenKitchen[id]=true;render();}};
document.onchange=function(e){e=e||window.event;var t=e.target||e.srcElement,id=t.getAttribute&&t.getAttribute("data-product");if(id)setAvailability(id,!!t.checked);};
})();
